version: '3.8'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/mean-crud-01
    depends_on:
      - mongo

  client:
    image: node:20.10.0
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    ports:
      - "4200:4200"
    command: sh -c "cd /usr/src/app && pnpm install && pnpm run start"
    depends_on:
      - server

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
