version: '3.8'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - DB_MONGO=mongodb+srv://axelwarneke:admin123@cluster0.d7eybsc.mongodb.net/mean-products
    depends_on:
      - mongo
