version: '3.8'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/
    environment:
      - DB_MONGO=mongodb+srv://axelwarneke:admin123@cluster0.d7eybsc.mongodb.net/mean-products
    depends_on:
      - mongo

  client:
    image: node:20.10.0
    working_dir: ./client:/src/app
    volumes:
      - ./client:/src/app
    ports:
      - "4200:4200"
    command: sh -c "cd /usr/src/app && pnpm install && pnpm run start"
    depends_on:
      - server

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
